# Generated by Django 3.0.8 on 2021-03-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
