# Generated by Django 3.0.8 on 2021-03-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210325_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_CEO',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=True),
        ),
    ]
